/** Oma & Sons integration: existing Cart layout backed by server cart lines and variant-aware mutations. */
import { Link, useLocation } from "wouter";
import { LockKeyhole, X } from "lucide-react";
import { DesktopHeader, Footer, MobileHeader, WhatsAppWidget } from "../components/layout/SiteChrome";
import { QuantityControl } from "../components/cart/QuantityControl";
import { useStorefront } from "../state/StorefrontContext";
import { resolveAssetUrl, handleImageError } from "../lib/api";
import { formatNaira } from "../utils/pricing";

function CartSummary({ lines, checkout, setCheckout, onCheckout }) { const subtotal = lines.reduce((sum, line) => sum + Number(line.subtotal || line.price * line.quantity), 0); const delivery = checkout.deliveryMethod === "express" ? 5000 : checkout.deliveryMethod === "pickup" ? 0 : 2500; return <aside className="cart-summary"><h2>Order Summary</h2><div className="summary-row"><span>Subtotal ({lines.length} items)</span><strong>{formatNaira(subtotal)}</strong></div><label className="summary-delivery">Delivery Estimate<select value={checkout.deliveryMethod} onChange={(event) => setCheckout({ ...checkout, deliveryMethod: event.target.value })}><option value="standard">Lagos State (1–2 Days)</option><option value="express">Express Delivery</option><option value="pickup">Store Pickup</option></select></label><div className="summary-row"><span>Estimated Fee</span><strong>{checkout.deliveryMethod === "pickup" ? "Calculated next step" : formatNaira(delivery)}</strong></div><div className="summary-total"><span>Total</span><strong>{formatNaira(subtotal + delivery)}</strong></div><button className="primary-button" disabled={!lines.length} onClick={onCheckout}>Proceed to Checkout →</button><p className="secure-row"><LockKeyhole size={14} /> Secure Checkout</p></aside>; }

export default function CartPage() {
  const [, setLocation] = useLocation(); const { cartLines, cartLoading, cartError, checkout, setCheckout, changeQuantity, removeLine } = useStorefront();
  return <div><DesktopHeader /><MobileHeader compact cartOnly /><main className="cart-page page-wrap"><div className="cart-title-row"><div><h1>Your Cart</h1><p>Review your items before proceeding to checkout.</p></div><Link href="/shop" className="mobile-cart-continue mobile-only">→Continue Shopping</Link></div>{cartLoading ? <p className="inline-state">Loading your cart…</p> : cartError ? <p className="inline-state error-state">{cartError}</p> : cartLines.length ? <div className="cart-layout"><section className="cart-lines">{cartLines.map((line) => <article className="cart-line" key={line.id || line.variantId}><img src={resolveAssetUrl(line.image)} alt={line.name} onError={handleImageError} /><div className="cart-line-copy"><h2>{line.name}</h2><p>{line.category} · {line.variant}</p><strong className="mobile-only">{formatNaira(line.price)}</strong><QuantityControl quantity={line.quantity} onChange={(direction) => changeQuantity(line, direction)} /></div><strong className="cart-line-price desktop-only">{formatNaira(line.price * line.quantity)}</strong><button className="remove-line" onClick={() => removeLine(line)} aria-label={`Remove ${line.name}`}><X /></button></article>)}<Link href="/shop" className="desktop-cart-continue desktop-only">← Continue Shopping</Link></section><CartSummary lines={cartLines} checkout={checkout} setCheckout={setCheckout} onCheckout={() => setLocation("/checkout")} /></div> : <section className="empty-cart"><h2>Your cart is empty</h2><p>Browse the current collection to continue shopping.</p><Link href="/shop" className="primary-button">Continue Shopping</Link></section>}</main><Footer /><WhatsAppWidget /></div>;
}
