/** Oma & Sons integration: existing Product Detail composition backed by API product, variant, wishlist, and cart data. */
import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useRoute, useSearch } from "wouter";
import { ChevronDown, Heart, ShoppingBag, Truck, Award } from "lucide-react";
import { DesktopHeader, Footer, MobileHeader, WhatsAppWidget } from "../components/layout/SiteChrome";
import { ProductCard } from "../components/catalogue/ProductCard";
import { QuantityControl } from "../components/cart/QuantityControl";
import { categoryLabels } from "../data/products";
import { api, resolveAssetUrl, resolveProductImage, handleImageError } from "../lib/api";
import { formatNaira } from "../utils/pricing";
import { useStorefront } from "../state/StorefrontContext";

function ReassuranceRows() { return <div className="detail-reassurance"><p><Truck /> <span><strong>Free Delivery</strong><br />On orders over ₦100,000 within Lagos.</span></p><p><Award /> <span><strong>2 Year Warranty</strong><br />Official manufacturer guarantee included.</span></p></div>; }
function Disclosure({ title, children }) { const [open, setOpen] = useState(false); return <section className="detail-disclosure"><button onClick={() => setOpen(!open)}>{title}<ChevronDown className={open ? "flip" : ""} /></button>{open && <div>{children}</div>}</section>; }

export default function ProductDetailPage() {
  const [, params] = useRoute("/product/:slug"); const [, setLocation] = useLocation(); const search = useSearch(); const { savedIds, toggleSaved, addToCart, auth } = useStorefront();
  const [product, setProduct] = useState(null); const [related, setRelated] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [quantity, setQuantity] = useState(1); const [selectedId, setSelectedId] = useState(null);
  useEffect(() => { let active = true; setLoading(true); api.getProduct(params?.slug).then(async (payload) => { if (!active) return; setProduct(payload); const first = payload?.variants?.[0]; setSelectedId(first?.id || null); const embeddedRecommendations = Array.isArray(payload?.recommendations) ? payload.recommendations : []; if (embeddedRecommendations.length) { setRelated(embeddedRecommendations.slice(0, 4)); return; } try { const all = await api.listProducts({ category: payload.category }); if (active) setRelated((Array.isArray(all) ? all : all?.results || []).filter((item) => item.slug !== payload.slug).slice(0, 4)); } catch { if (active) setRelated([]); } }).catch(() => { if (active) setError("Product not found."); }).finally(() => active && setLoading(false)); return () => { active = false; }; }, [params?.slug]);
  useEffect(() => { if (!product || !auth?.token) return; const shouldAutosave = new URLSearchParams(search).get("autosave") === "1"; if (!shouldAutosave) return; setLocation(`/product/${params?.slug}`, { replace: true }); (async () => { try { await toggleSaved(product.id); } catch {} })(); }, [product, auth?.token, search]);
  const selected = useMemo(() => product?.variants?.find((item) => item.id === selectedId) || product?.variants?.[0], [product, selectedId]);
  const title = product?.category === "kitchen-appliances" ? "Complete Your Kitchen" : "Complete Your Wardrobe";
  const change = (direction) => setQuantity((current) => Math.max(1, current + direction));
  const save = async () => { if (!auth?.token) { setLocation(`/login?reason=save&product=${params?.slug}`); return; } try { await toggleSaved(product.id); } catch {} };
  const add = async () => { if (!selected?.id || selected.available === false) return; try { await addToCart(selected.id, quantity); } catch (e) { window.dispatchEvent(new CustomEvent("oma-notice", { detail: { message: e.message, tone: "error" } })); } };
  if (loading) return <div><DesktopHeader /><MobileHeader compact cartOnly back /><main className="detail-page page-wrap"><p className="inline-state">Loading product…</p></main><Footer /></div>;
  if (error || !product) return <div><DesktopHeader /><MobileHeader compact cartOnly back /><main className="detail-page page-wrap"><p className="inline-state error-state">{error || "Product not found."}</p></main><Footer /></div>;
  const price = selected?.price || product.price; const saved = savedIds.includes(product.id);
  return <div><DesktopHeader activeCategory={product.category} /><MobileHeader compact cartOnly back /><main className="detail-page page-wrap"><div className="breadcrumb desktop-only"><Link href="/">Home</Link><span>›</span><Link href={`/shop?category=${product.category}`}>{categoryLabels[product.category] || product.category_name}</Link><span>›</span><span>{product.name}</span></div><div className="detail-layout"><section className="detail-gallery"><button className={`detail-heart ${saved ? "is-saved" : ""}`} onClick={save} aria-label="Save product"><Heart fill={saved ? "currentColor" : "none"} /></button><div className="detail-main-image"><img src={resolveAssetUrl(selected?.image) || resolveProductImage(product)} alt={product.name} onError={handleImageError} /></div></section><section className="detail-info"><span className="product-collection">{product.collection}</span><span className="mobile-only best-seller">{product.badge === "BEST SELLER" ? "BEST SELLER" : ""}</span><h1>{product.name}</h1><div className="detail-price"><strong>{formatNaira(price)}</strong>{product.formerPrice && <del>{formatNaira(product.formerPrice)}</del>}</div><p className="detail-description">{product.description}</p>{product.variants?.length > 1 && <label className="variant-select"><span>Choose an option</span><select value={selectedId || ""} onChange={(event) => setSelectedId(Number(event.target.value))}>{product.variants.map((item) => <option key={item.id} value={item.id}>{item.variant_name || item.size} — {formatNaira(item.price)}</option>)}</select></label>}<p className={`stock-message ${selected?.available === false ? "is-unavailable" : ""}`}>{selected?.available === false ? "Currently unavailable" : `${selected?.stock_quantity ?? 0} available`}</p><div className="mobile-detail-purchase mobile-only"><button className="primary-button" disabled={selected?.available === false} onClick={add}><ShoppingBag size={16} /> Add to Cart</button></div><div className="detail-purchase desktop-only"><QuantityControl quantity={quantity} onChange={change} /><button className="primary-button" disabled={selected?.available === false} onClick={add}><ShoppingBag size={16} /> Add to Cart</button></div><div className="desktop-only"><ReassuranceRows /></div><div className="mobile-detail-disclosures mobile-only"><Disclosure title="Product Details"><p>{product.description}</p></Disclosure><Disclosure title="Shipping & Returns"><ReassuranceRows /></Disclosure><Disclosure title="Store Availability"><p><strong>Ago Palace Way Store</strong><br />123 Main Road, Lagos</p><p><strong>Ijesha Store</strong><br />45 Market Street, Lagos</p></Disclosure></div></section></div><section className="recommendations"><h2>{title}</h2><div>{related.map((item) => <ProductCard key={item.id} product={item} variant="recommendation" showCart />)}</div></section></main><Footer /><WhatsAppWidget /></div>;
}
