/** Oma & Sons integration: backend catalog data inside the existing Figma-aligned Shop layout. */
import { useEffect, useMemo, useState } from "react";
import { Link, useSearch } from "wouter";
import { ChevronDown, SlidersHorizontal, X } from "lucide-react";
import { DesktopHeader, Footer, MobileHeader, WhatsAppWidget } from "../components/layout/SiteChrome";
import { ProductCard } from "../components/catalogue/ProductCard";
import { categoryLabels } from "../data/products";
import { navCategories } from "../data/content";
import { api } from "../lib/api";

const description = "Curated, high-quality selections for everyday elegance. Sustainable fashion without compromising on style.";
function FilterForm({ filters, setFilters, mobile = false, close }) { const apply = () => close?.(); return <div className={mobile ? "mobile-filter-body" : "filter-rail"}>{!mobile && <><h3>Categories</h3><button className={!filters.category ? "is-current" : ""} onClick={() => setFilters({ ...filters, category: "" })}>All Products</button>{navCategories.map((category) => <button key={category} className={filters.category === category ? "is-current" : ""} onClick={() => setFilters({ ...filters, category })}>{categoryLabels[category]}</button>)}<h3>Price Range</h3></>}{mobile && <><div className="filter-sheet-title"><h3>Filter & Sort</h3><button onClick={close}><X /></button></div><h4>Category</h4><div className="mobile-category-buttons"><button className={!filters.category ? "is-current" : ""} onClick={() => setFilters({ ...filters, category: "" })}>All Products</button>{navCategories.map((category) => <button key={category} className={filters.category === category ? "is-current" : ""} onClick={() => setFilters({ ...filters, category })}>{categoryLabels[category]}</button>)}</div><h4>Price Range</h4></>}{<div className="price-inputs"><input value={filters.minPrice} onChange={(event) => setFilters({ ...filters, minPrice: event.target.value })} placeholder="Min ₦" inputMode="numeric" /><span>–</span><input value={filters.maxPrice} onChange={(event) => setFilters({ ...filters, maxPrice: event.target.value })} placeholder="Max ₦" inputMode="numeric" /></div>}{mobile && <><h4>Sort by</h4><SortSelect value={filters.sort} onChange={(sort) => setFilters({ ...filters, sort })} /></>}<button className="apply-filter" onClick={apply}>Apply</button></div>; }
function SortSelect({ value, onChange }) { return <label className="sort-select"><span>Sort by:</span><select value={value} onChange={(event) => onChange(event.target.value)}><option value="featured">Featured</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option><option value="newest">Newest</option></select><ChevronDown /></label>; }

export default function ShopPage() {
  const params = new URLSearchParams(useSearch()); const routeCategory = params.get("category") || "";
  const [filters, setFilters] = useState({ category: routeCategory, minPrice: "", maxPrice: "", sort: "featured" });
  const [search, setSearch] = useState(""); const [products, setProducts] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [visibleCount, setVisibleCount] = useState(4); const [mobileFiltersOpen, setMobileFiltersOpen] = useState(false);
  useEffect(() => { setFilters((previous) => ({ ...previous, category: routeCategory })); setVisibleCount(4); }, [routeCategory]);
  useEffect(() => { let active = true; setLoading(true); const timer = window.setTimeout(() => { api.listProducts({ category: filters.category, min_price: filters.minPrice, max_price: filters.maxPrice, sort: filters.sort, search }).then((payload) => { if (active) { setProducts(Array.isArray(payload) ? payload : payload?.results || []); setError(""); } }).catch(() => { if (!active) return; setProducts([]); setError("We couldn't load products right now. Please try again shortly."); }).finally(() => active && setLoading(false)); }, 180); return () => { active = false; window.clearTimeout(timer); }; }, [filters.category, filters.minPrice, filters.maxPrice, filters.sort, search]);
  const selectedName = filters.category ? categoryLabels[filters.category] : "All Products"; const heading = filters.category === "clothes" ? "Premium Thrift Clothes" : selectedName === "All Products" ? "Premium Thrift Finds" : `Premium ${selectedName}`; const visibleProducts = useMemo(() => products.slice(0, filters.category ? 4 : visibleCount), [products, filters.category, visibleCount]); const canLoad = !filters.category && visibleCount < products.length;
  return <div><DesktopHeader activeCategory={filters.category} /><MobileHeader compact /><main className="shop-page page-wrap"><div className="breadcrumb desktop-only"><Link href="/">Home</Link><span>›</span><span>Shop</span>{filters.category && <><span>›</span><span>{selectedName}</span></>}</div><div className="shop-search"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search products..." aria-label="Search products" /><span>⌕</span></div><div className="shop-title-row"><div><h1>{heading}</h1><p>{description}</p></div><div className="desktop-only"><SortSelect value={filters.sort} onChange={(sort) => setFilters({ ...filters, sort })} /></div></div><div className="mobile-shop-controls mobile-only"><span>{products.length} Products</span><button onClick={() => setMobileFiltersOpen(true)}><SlidersHorizontal size={14} /> Filter & Sort</button></div><div className="shop-rule" /><div className="shop-layout"><aside className="desktop-only"><FilterForm filters={filters} setFilters={setFilters} /></aside><section className="shop-grid">{loading && <p className="inline-state">Loading products…</p>}{!loading && error && <p className="inline-state error-state">{error}</p>}{!loading && !error && !visibleProducts.length && <p className="inline-state">No products found.</p>}{!loading && !error && visibleProducts.map((product) => <ProductCard key={product.id} product={product} variant="shop" showCart />)}</section></div>{canLoad && <button className="load-more" onClick={() => setVisibleCount((count) => count + 4)}>Load More <span className="desktop-only">Products</span> <ChevronDown size={15} /></button>}</main>{mobileFiltersOpen && <div className="filter-sheet-layer mobile-only" onClick={() => setMobileFiltersOpen(false)}><aside className="filter-sheet" onClick={(event) => event.stopPropagation()}><FilterForm filters={filters} setFilters={setFilters} mobile close={() => setMobileFiltersOpen(false)} /></aside></div>}<Footer /><WhatsAppWidget /></div>;
}
