/** Oma & Sons integration: existing Sign Up visual surface backed by the Django registration endpoint. */
import { useEffect, useState } from "react";
import { Link, useLocation, useSearch } from "wouter";
import { Eye, EyeOff } from "lucide-react";
import { assets } from "../data/assets";
import { useStorefront } from "../state/StorefrontContext";

export default function SignUpPage() {
  const [, setLocation] = useLocation(); const search = useSearch(); const { register } = useStorefront(); const [show, setShow] = useState(false); const [form, setForm] = useState({ first_name: "", last_name: "", email: "", phone_number: "", password: "" }); const [agreedToTerms, setAgreedToTerms] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const update = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const params = new URLSearchParams(search); const saveProduct = params.get("reason") === "save" ? params.get("product") : null;
  useEffect(() => { if (saveProduct) window.dispatchEvent(new CustomEvent("oma-notice", { detail: { message: "Sign in to save this product.", tone: "success" } })); }, [saveProduct]);
  const submit = async () => { if (!agreedToTerms) { setError("Please agree to the Terms of Service and Privacy Policy to continue."); return; } setBusy(true); setError(""); try { await register(form); setLocation(saveProduct ? `/product/${saveProduct}?autosave=1` : "/"); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <main className="auth-page"><section className="auth-card signup-card"><Link href="/" className="auth-logo" aria-label="Omawhiyte & Sons Dynamic Ventures home"><img src={assets.logo} alt="Omawhiyte & Sons Dynamic Ventures" /></Link><h1>Create Account</h1><p className="auth-lede desktop-only">Create your account to start shopping.</p><p className="auth-lede mobile-only">Join Omawhiyte & Sons for a seamless shopping experience.</p><div className="address-grid"><label className="form-field"><span>First Name</span><input value={form.first_name} onChange={update("first_name")} /></label><label className="form-field"><span>Last Name</span><input value={form.last_name} onChange={update("last_name")} /></label></div><label className="form-field"><span>Email Address</span><input value={form.email} onChange={update("email")} placeholder="you@example.com" type="email" /></label><label className="form-field"><span>Phone Number</span><input value={form.phone_number} onChange={update("phone_number")} placeholder="+234..." /></label><label className="form-field password-field"><span>Password</span><input value={form.password} onChange={update("password")} type={show ? "text" : "password"} placeholder="••••••••" /><button className="password-toggle" type="button" onClick={() => setShow(!show)} aria-label={show ? "Hide password" : "Show password"}>{show ? <EyeOff /> : <Eye />}</button></label><p className="password-help">Must be at least 6 characters.</p><label className="simple-check"><input type="checkbox" checked={agreedToTerms} onChange={(event) => setAgreedToTerms(event.target.checked)} /> I agree to the Terms of Service and Privacy Policy</label>{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={busy || !agreedToTerms} onClick={submit}>{busy ? "Creating account…" : "Create Account →"}</button><p className="auth-switch">Already have an account? <Link href={saveProduct ? `/login?reason=save&product=${saveProduct}` : "/login"}>Log in</Link></p></section></main>;
}
